; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.2.3 on Sun Mar 14 2021 16:28:18 GMT-0400 (Eastern Daylight Time)
M83            ; relative extruder moves
G1 E-3 F3600  ; retract 3mm of filament
G91            ; relative positioning
G1 Z5 F99999     ; lift Z by 5mm
G90						; abs cords
M98 P"0:/macros/PurgeBucket/moveToPurgeBucket"

